config/routes.rb
Rails.application.routes.draw do
  resources :requests
  get 'users/register'

  get 'home/contact'

  get 'home/medications'

  get 'home/about'

  get 'home/index'

  post 'home/send_contact_message'

  post 'medications/set_page_count'

  post 'medications/search_meds'

  post 'inventories/set_page_count'

  post 'inventories/search_inv'

  post 'events/set_page_count'

  post 'events/search_events'

  get 'events/past_events'

  get 'events/parent_past_events'

  get 'events/student_past_events'

  get 'events/student_view'

  get 'events/parent_view'

  post 'events/set_past_page_count'

  post 'events/search_past_events'

  get 'events/complete'

  get 'events/incomplete'

  post 'events/change_notes'

  post 'users/register_district_admin'

  post 'users/update'

  get 'users/dashboard'

  get 'inventories/new'

  post 'inventories/new_item'

  post 'inventories/change_notes'

  post 'inventories/change_amount'

  post 'users/set_password'

  post 'users/create_and_email'

  get 'forms/new'

  post 'forms/new_form'

  post 'forms/search_forms'

  post 'forms/set_page_count'

  post 'forms/change_body'

  get 'forms/parent_view'

  get 'forms/parent_view'

  get 'forms/approve_form'

  post 'requests/create_request'

  post 'requests/approve'

  get 'nurses/associate_page', to: 'nurses#associate'
  post 'nurses/associate', to: 'nurses#associatestudentparent'

  get 'admins/associate_page', to: 'admins#associate'
  post 'admins/associate', to: 'admins#associatestudentparent'

  resources :password_sets
  resources :forms
  resources :events
  resources :inventories
  resources :medications, only: [:index, :show]
  resources :admins, only: [:index]
  resources :nurses, only: [:index]
  resources :students, only: [:index]
  resources :parents, only: [:index]
  resources :users

  root "home#index"

  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match "*path" => "home#index", via: [:get, :post]

end

app/views/admins/associate.html.erb
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h3>Associate a Parent and Student</h3>
        </div>
        <%= form_for admins_associate_page_path, url: admins_associate_path do %>

          <div class="form-outline mb-4">
            <%= label_tag :parent, "Parent", class:"form-label" %>
            <%= select_tag :parent, options_for_select(@parents_info), class:"form-control" %>
          </div>
          <div class="form-outline mb-4">
            <%= label_tag :student, "Student", class:"form-label" %>
            <%= select_tag :student, options_for_select(@students_info), class:"form-control" %>
          </div>

          <div class="mt-5 text-center">
            <%=link_to "Cancel", admins_path, class:"btn btn-danger profile-button"%>
            <%= submit_tag 'Submit', name: 'submit', class:"btn btn-primary profile-button"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admins/index.html.erb
<% content_for(:html_title) { "Admin Dashboard" } %>
<%= stylesheet_link_tag    'nurses', media: 'all' %>

<main role="main">
  <div class="jumbotron">
    <div class="container mb">
      <h1 class="display-3 ">Welcome, <%= @current_user.first_name %></h1>
    </div>
  </div>

  <div class="container">
    <!-- Example row of columns -->
    <div class="album py-5">
      <div class="container homeContainer">
        <div class="row justify-content-center">
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <h2 class="top-content">View Parents and Students</h2>
              <%= link_to "People", users_path, class: "btn btn-secondary"%>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <h2 class="top-content">See Medication Information</h2>
              <%= link_to "All Medications", medications_path, class: "btn btn-secondary"%>
            </div>
          </div>
        </div>

        <div class="row justify-content-center">
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <h2 class="top-content">Associate Students with Parents</h2>
              <%= link_to "Association", admins_associate_page_path, class: "btn btn-secondary"%>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <h2 class="top-content">Add User to District</h2>
              <%= link_to "Invite User", new_user_path, class: "btn btn-secondary"%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>

  </div> <!-- /container -->
</main>