config/routes.rb
Rails.application.routes.draw do
  resources :requests
  get 'users/register'

  get 'home/contact'

  get 'home/medications'

  get 'home/about'

  get 'home/index'

  post 'home/send_contact_message'

  post 'medications/set_page_count'

  post 'medications/search_meds'

  post 'inventories/set_page_count'

  post 'inventories/search_inv'

  post 'events/set_page_count'

  post 'events/search_events'

  get 'events/past_events'

  get 'events/parent_past_events'

  get 'events/student_past_events'

  get 'events/student_view'

  get 'events/parent_view'

  post 'events/set_past_page_count'

  post 'events/search_past_events'

  get 'events/complete'

  get 'events/incomplete'

  post 'events/change_notes'

  post 'users/register_district_admin'

  post 'users/update'

  get 'users/dashboard'

  get 'inventories/new'

  post 'inventories/new_item'

  post 'inventories/change_notes'

  post 'inventories/change_amount'

  post 'users/set_password'

  post 'users/create_and_email'

  get 'forms/new'

  post 'forms/new_form'

  post 'forms/search_forms'

  post 'forms/set_page_count'

  post 'forms/change_body'

  get 'forms/parent_view'

  get 'forms/parent_view'

  get 'forms/approve_form'

  post 'requests/create_request'

  post 'requests/approve'

  get 'nurses/associate_page', to: 'nurses#associate'
  post 'nurses/associate', to: 'nurses#associatestudentparent'

  get 'admins/associate_page', to: 'admins#associate'
  post 'admins/associate', to: 'admins#associatestudentparent'

  resources :password_sets
  resources :forms
  resources :events
  resources :inventories
  resources :medications, only: [:index, :show]
  resources :admins, only: [:index]
  resources :nurses, only: [:index]
  resources :students, only: [:index]
  resources :parents, only: [:index]
  resources :users

  root "home#index"

  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match "*path" => "home#index", via: [:get, :post]

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :student

  def self.create_event_from_request(request)
    start = request.start_date
    end_date = request.end_date
    Date.new(start.year, start.month, start.day).upto(Date.new(end_date.year, end_date.month, end_date.day)) do |day|
      current_dose = 1
      unless weekend?(day)
        request.daily_doses.to_i.times do
          case current_dose
          when 1
            create_event(request, DateTime.new(day.year, day.month, day.day, request.time1.hour, request.time1.min, 0))
          when 2
            create_event(request, DateTime.new(day.year, day.month, day.day, request.time2.hour, request.time2.min, 0))
          when 3
            create_event(request, DateTime.new(day.year, day.month, day.day, request.time3.hour, request.time3.min, 0))
          when 4
            create_event(request, DateTime.new(day.year, day.month, day.day, request.time3.hour, request.time3.min, 0))
          end
          current_dose += 1
        end
      end
    end
  end


  def self.weekend?(day)
    (day.wday == 0 || day.wday == 6)
  end

  def self.create_event(request, time)
    Event.create!(time: time, student_id: request.student_id, med_id: request.med_id, complete: false, notes: request.notes, district: request.district_id, amount: request.amount)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :students
  has_many :parents
  has_many :nurses
  has_many :admins

  has_secure_password
  before_save { |user| user.email = user.email.downcase }
  before_save :create_session_token
  VALID_EMAIL_REGEX = /\A([\w+\-]\.?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  VALID_PHONE_REGEX = /\A(?:\+?\d{1,3}\s*-?)?\(?(?:\d{3})?\)?[- ]?\d{3}[- ]?\d{4}\z/i
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, on: :save
  validates :password_confirmation, presence: true, on: :save
  validates :password, confirmation: { case_sensitive: true }, on: :save
  validates :phone, allow_blank: true, allow_nil: true, format: { with: VALID_PHONE_REGEX }
  validates :role, presence: true

  def self.search_users(type, term, district_id, role)
    return User.where(district_id: district_id) if term.blank? && role == 'Admin'
    return User.where(district_id: district_id, role: %w[Student Parent]) if term.blank? && role == 'Nurse'

    case role
    when 'Admin'
      if type == 'Name'
        User.search_name(term.split, district_id, role)
      else
        User.where('lower(role) = ? and district_id = ?', term.downcase, district_id)
      end
    else
      User.search_name(term.split, district_id, role)
    end
  end

  def send_password_set
    generate_token(:password_set_token)
    self.password_set_sent_at = Time.zone.now
    save!
    ApplicationMailer.set_password(self).deliver
  end

  private

  def create_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def self.search_name(name, district_id, role)
    if role == 'Admin'
      if name.count == 1
        User.where('lower(first_name) = ? and district_id = ?', name[0].downcase, district_id)
      else
        User.where('lower(first_name) = ? and lower(last_name) = ? and district_id = ?', name[0].downcase, name[1].downcase,district_id)
      end
    else
      if name.count == 1
        User.where('lower(first_name) = ? and district_id = ? and lower(role) IN (?)', name[0].downcase, district_id, %w[student parent])
      else
        User.where('lower(first_name) = ? and lower(last_name) = ? and district_id = ? and lower(role) IN (?)', name[0].downcase, name[1].downcase,district_id, %w[student parent])
      end
    end
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :is_nurse, only: [:index, :past_events, :complete, :incomplete, :change_notes]
  before_action :is_parent, only: [:parent_past_events, :parent_view]
  before_action :is_student, only: [:student_past_events, :student_view]
  before_action :belongs_to_district, only: [:show]
  # GET /events
  # GET /events.json
  def index
    @pages = session[:page_count]
    @selection = session[:search_term]

    if @pages.nil?
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).reorder("time ASC").page(params[:page]).per_page(50)
      else
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(50)
      end
    else
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).reorder("time ASC").page(params[:page]).per_page(@pages)
      else
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(@pages)
      end
    end
  end

  def parent_view
    @pages = session[:page_count]
    @selection = session[:search_term]

    if @pages.nil?
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).reorder("time ASC").page(params[:page]).per_page(50)
      else
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(50)
      end
    else
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).reorder("time ASC").page(params[:page]).per_page(@pages)
      else
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(@pages)
      end
    end
    render 'events/index'
  end

  def student_view
    @pages = session[:page_count]
    @selection = session[:search_term]

    if @pages.nil?
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).reorder("time ASC").page(params[:page]).per_page(50)
      else
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(50)
      end
    else
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).reorder("time ASC").page(params[:page]).per_page(@pages)
      else
        @events = Event.where(complete: false, district: @current_user.district_id.to_i).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(@pages)
      end
    end
    render 'events/index'
  end

  def past_events
    @pages = session[:page_count]
    @selection = session[:search_term]
    if @pages.nil?
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: true).reorder("time ASC").page(params[:page]).per_page(50)
      else
        @events = Event.where(complete: true).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(50)
      end
    else
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: true).reorder("time ASC").page(params[:page]).per_page(@pages)
      else
        @events = Event.where(complete: true).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(@pages)
      end
    end
  end

  # GET /events/parent_past_events
  def parent_past_events
    @pages = session[:page_count]
    @selection = session[:search_term]
    if @pages.nil?
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: true).reorder("time ASC").page(params[:page]).per_page(50)
      else
        @events = Event.where(complete: true).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(50)
      end
    else
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: true).reorder("time ASC").page(params[:page]).per_page(@pages)
      else
        @events = Event.where(complete: true).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(@pages)
      end
    end
    render 'events/past_events'
  end

  def student_past_events
    @pages = session[:page_count]
    @selection = session[:search_term]
    if @pages.nil?
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: true).reorder("time ASC").page(params[:page]).per_page(50)
      else
        @events = Event.where(complete: true).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(50)
      end
    else
      if @selection.nil? or @selection.blank?
        @events = Event.where(complete: true).reorder("time ASC").page(params[:page]).per_page(@pages)
      else
        @events = Event.where(complete: true).where("student_id = ? OR med_id = ?", @selection.downcase, @selection.downcase).reorder("time ASC").page(params[:page]).per_page(@pages)
      end
    end
    render 'events/past_events'
  end

  def set_page_count
    unless params[:page_count].nil?
      @pages = params[:page_count][:page_count]
      session[:page_count] = @pages.to_i
    end
    case @current_user.role
    when 'Parent'
      redirect_to events_parent_view_path
    when 'Student'
      redirect_to events_student_view_path
    when 'Nurse'
      redirect_to events_path
    end
  end

  def search_events
    session[:search_term] = params[:search_term][:search_term] unless params[:search_term].nil?
    case @current_user.role
    when 'Parent'
      redirect_to events_parent_view_path
    when 'Student'
      redirect_to events_student_view_path
    when 'Nurse'
      redirect_to events_path
    end
  end

  def set_past_page_count
    unless params[:page_count].nil?
      @pages = params[:page_count][:page_count]
      session[:page_count] = @pages.to_i
    end
    case @current_user.role
    when 'Parent'
      redirect_to events_parent_past_events_path
    when 'Student'
      redirect_to events_student_past_events_path
    when 'Nurse'
      redirect_to events_past_events_path
    end
  end

  def search_past_events
    session[:search_term] = params[:search_term][:search_term] unless params[:search_term].nil?
    case @current_user.role
    when 'Parent'
      redirect_to events_parent_past_events_path
    when 'Student'
      redirect_to events_student_past_events_path
    when 'Nurse'
      redirect_to events_past_events_path
    end
  end

  def complete
    if params[:id].nil?
      flash[:error] = "There was a problem marking this event as complete"
    else
      @eventID = params[:id]
      student_id = params[:student_id]
      med_id = params[:med_id]
      med_amount = params[:amount]
      district_id = params[:district_id]
      current_inventory = Inventory.where(studentID: student_id, med_id: med_id, districtID: district_id)

      if current_inventory.first.nil?
        current_inventory = Inventory.where(studentID: nil, med_id: med_id, districtID: district_id)
      end
      total = current_inventory.first.amount

      if (total - med_amount.to_i).negative?
        flash[:error] = "Unable to mark event as complete. You want to remove #{med_amount} doses, but you only have #{total} doses left!"
        redirect_to events_path and return
      end

      @event = Event.where(id: @eventID).update_all(complete: true)
      @inventory = current_inventory.update_all(amount: total - med_amount.to_i)
      flash[:notice] = "Event has been marked as complete"
    end
    redirect_to events_past_events_path
  end

  def incomplete
    if params[:id].nil?
      flash[:error] = "There was a problem marking this event as incomplete"
    else
      @eventID = params[:id]
      student_id = params[:student_id]
      med_id = params[:med_id]
      med_amount = params[:amount]
      district_id = params[:district_id]
      current_inventory = Inventory.where(studentID: student_id, med_id: med_id, districtID: district_id)

      if current_inventory.first.nil?
        current_inventory = Inventory.where(studentID: nil, med_id: med_id, districtID: district_id)
      end
      total = current_inventory.first.amount

      @event = Event.where(id: @eventID).update_all(complete: false)
      @inventory = current_inventory.update_all(amount: total + med_amount.to_i)
      flash[:notice] = "Event has been marked as incomplete"
    end
    redirect_to events_path
  end

  def change_notes
    if params[:notes].nil?
      flash[:error] = "There was a problem editing this note"
    else
      @newNotes = params[:notes][:notes]
      @id = params[:notes][:id]
      @complete = params[:notes][:complete]
      @event = Event.where(id: @id).update_all(notes: @newNotes)
      flash[:notice] = "Notes have been updated successfully"
    end
    if @complete == 'true'
      redirect_to events_past_events_path
    else
      redirect_to events_path

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mb-2 d-flex flex-column">
    <%= f.label :time %>
    <div class="d-flex flex-row align-items-center">
      <%= f.datetime_select :time, {}, class: "form-select w-auto" %>
    </div>
  </div>
  <div class="form-group mb-2">
    <%= f.label :student_id %><br>
    <%= f.select :student_id, @students, {}, class: "form-select", onchange: "getMedications(this.value)" %>
  </div>
  <div class="form-group mb-2">
    <%= f.label :med_id, "Medication" %><br>
    <%= f.select :med_id, {}, {}, class: "form-control" %>
  </div>
  <div>
    <%= f.label :amount %>
    <%= f.number_field :amount, class: "form-control", onkeyup: "checkNewEvent(this)" %>
  </div>
  <div class="form-group mb-2">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="form-group mb-2">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, class: "form-control" %>
  </div>
  <%= f.hidden_field :district, value: @current_user.district_id %>
  <div class="actions mb-2">
    <%= f.submit 'Create Event', class: "btn btn-primary", id: 'submit', disabled: 'true' %>
    <a href="javascript:history.back()" class="btn btn-secondary">Back</a>
  </div>
<% end %>

app/views/events/_medications.html.erb
<%= select :event, :med_id, @medications, {},  { class: "form-select" } %>

app/views/events/index.html.erb
<% content_for(:html_title) { "Events" } %>
<%= stylesheet_link_tag    'events', media: 'all' %>

<div class="container">
  <h1>Incomplete Events</h1>
  <div class="input-group">
    <div class="form-outline fl">
      <%= form_for :search_term, url: events_search_events_path do |f|  %>
        <div class="input-group align-items-center">
          <%= f.label :search_term, "Student ID: ", class: "form-label" %>
          <%= f.number_field :search_term, class: "form-control", :html => {:id => "form1", :name => "form1"}, id:"form1" %>
          <%= f.submit :Search, class: "btn btn-primary",  id: "submit"%>
        </div>
      <% end %>
    </div>
  </div>
  <div class="fr">
    <%= form_for :page_count, :url => events_set_page_count_path do |f|  %>
      <div class="form-group"
      <%= f.label :page_count, "Results per page: " %>
      <%= f.select :page_count, options_for_select([10, 25, 35, 50, 75, 100, 250], @pages), {}, :onchange => 'this.form.submit()'%>
      </div>
    <% end %>
    </div>
<table id="dtBasicExample" class="table table-striped table-bordered table-sm mt-2" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th class="th-sm">Student Name
    </th>
    <th class="th-sm">Student ID
    </th>
    <th class="th-sm">Time
    </th>
    <th class="th-sm">Medication
    </th>
    <th class="th-sm">Amount
    </th>
    <th class="th-sm">Notes
    </th>
  </tr>
  </thead>
  <tbody>
  <% if @current_user.role == "Nurse" %>
    <% @events.each do |event| %>
      <% @student = User.where(id: event.student_id).first %>
      <tr>
        <% unless @student.nil? %>
          <td><%= @student.first_name + @student.last_name %></td>
        <% else %>
          <td>No Student Found</td>
        <% end %>
        <td><%= event.student_id %></td>
        <td><%= event.time %></td>
        <% if !Inventory.where(med_id: event.med_id).first.nil? %>
          <td><%= Inventory.where(med_id: event.med_id).first.medName %></td>
        <% elsif !Medication.find(event.med_id).nil? %>
          <td><%= Medication.find(event.med_id).brand_name %></td>
        <% else %>
          <td></td>
        <% end %>

        <td><%= event.amount %></td>
        <td><%= event.notes %></td>
        <td class="btn-center"><%= link_to 'More Information', event, id:event.student_id, class: "btn btn-primary btn-small" %></td>
      </tr>
    <% end %>
  <% end %>
  <% if @current_user.role == "Parent" %>
    <% @events.each do |event| %>
      <% @student = User.where(id: event.student_id).first %>
      <tr>
        <% @children = User.where(role: "Student", role_id: Parent.where(id: @current_user.role_id).first.student_ids).all %>
        <% unless @children.nil? %>
          <% @ids = @children.map{|s| s.id} %>
        <% end %>

        <% if @ids.include?(@student.id) %>
        <% unless @student.nil? %>
          <td><%= @student.first_name + @student.last_name %></td>
        <% else %>
          <td>No Student Found</td>
        <% end %>
        <td><%= event.student_id %></td>
        <td><%= event.time %></td>
        <%if !Medication.where(id: event.med_id).first.nil? %>
          <td><%= Medication.where(id: event.med_id).first.brand_name %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= event.notes %></td>
        <td class="btn-center"><%= link_to 'More Information', event, id:event.student_id, class: "btn btn-primary btn-small" %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  <% if @current_user.role == "Student" %>
    <% @events.each do |event| %>
      <% @student = User.where(id: event.student_id).first %>
      <tr>
        <% if @current_user == @student %>
        <% unless @student.nil? %>
          <td><%= @student.first_name + @student.last_name %></td>
        <% else %>
          <td>No Student Found</td>
        <% end %>
        <td><%= event.student_id %></td>
        <td><%= event.time %></td>
          <%if !Medication.where(id: event.med_id).first.nil? %>
            <td><%= Medication.where(id: event.med_id).first.brand_name %></td>
          <% else %>
            <td></td>
          <% end %>
        <td><%= event.notes %></td>
        <td class="btn-center"><%= link_to 'More Information', event, id:event.student_id, class: "btn btn-primary btn-small" %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  </tbody>
</table>
<div class="pagination">
  <%= will_paginate @events, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
</div>
</div>
<br>

app/views/events/new.html.erb
<% content_for(:html_title) { "New Event" } %>

<div class="container mt-2 mb-2">
  <h1>New Event</h1>

  <%= render 'form' %>

  <script type='text/javascript'>
    $(document).ready(function () {
        let studentId = $('#event_student_id').val();
        getMedications(studentId);
    })
  </script>
</div>

app/views/events/past_events.html.erb
<% content_for(:html_title) { "Past Events" } %>
<%= stylesheet_link_tag    'events', media: 'all' %>

<div class="container">
  <h1>Completed Events</h1>
  <div class="input-group">
    <%= form_for :search_term, url: events_search_past_events_path do |f|  %>
      <div class="input-group align-items-center">
        <%= f.label :search_term, "Student ID: ", class: "form-label" %>
        <%= f.number_field :search_term, class: "form-control", :html => {:id => "form1", :name => "form1"}, id:"form1" %>
        <%= f.submit :Search, class: "btn btn-primary",  id: "submit"%>
      </div>
    <% end %>
  </div>
  <div class="fr">
    <%= form_for :page_count, :url => events_set_past_page_count_path do |f|  %>
      <div class="form-group"
      <%= f.label :page_count, "Results per page: " %>
      <%= f.select :page_count, options_for_select([10, 25, 35, 50, 75, 100, 250], @pages), {}, :onchange => 'this.form.submit()'%>
      </div>
    <% end %>
    </div>
<table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
  <thead>
  <tr>
    <th class="th-sm">Student Name
    </th>
    <th class="th-sm">Student ID
    </th>
    <th class="th-sm">Time
    </th>
    <th class="th-sm">Medication
    </th>
    <th class="th-sm">Notes
    </th>
  </tr>
  </thead>
  <tbody>
  <% @events.each do |event| %>
  <% if @current_user.role == "Nurse" %>
    <% @events.each do |event| %>
      <% @student = User.where(id: event.student_id).first %>
      <tr>
        <% unless @student.nil? %>
          <td><%= @student.first_name + @student.last_name %></td>
        <% else %>
          <td>No Student Found</td>
        <% end %>
        <td><%= event.student_id %></td>
        <td><%= event.time %></td>
        <td><%= Medication.where(id: event.med_id).first.brand_name %></td>
        <td><%= event.notes %></td>
        <td class="btn-center"><%= link_to 'More Information', event, id:event.student_id, class: "btn btn-primary btn-small" %></td>
      </tr>
    <% end %>
  <% end %>
  <% if @current_user.role == "Parent" %>
    <% @events.each do |event| %>
      <% @student = User.where(id: event.student_id).first %>
      <tr>
        <% @children = User.where(role: "Student", role_id: Parent.where(id: @current_user.role_id).first.student_ids).all %>
        <% unless @children.nil? %>
          <% @ids = @children.map{|s| s.id} %>
        <% end %>

        <% if @ids.include?(@student.id) %>
        <% unless @student.nil? %>
          <td><%= @student.first_name + @student.last_name %></td>
        <% else %>
          <td>No Student Found</td>
        <% end %>
        <td><%= event.student_id %></td>
        <td><%= event.time %></td>
        <td><%= Medication.where(id: event.med_id).first.brand_name %></td>
        <td><%= event.notes %></td>
        <td class="btn-center"><%= link_to 'More Information', event, id:event.student_id, class: "btn btn-primary btn-small" %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  <% if @current_user.role == "Student" %>
    <% @events.each do |event| %>
      <% @student = User.where(id: event.student_id).first %>
      <tr>
        <% if @current_user == @student %>
        <% unless @student.nil? %>
          <td><%= @student.first_name + @student.last_name %></td>
        <% else %>
          <td>No Student Found</td>
        <% end %>
        <td><%= event.student_id %></td>
        <td><%= event.time %></td>
        <td><%= Medication.where(id: event.med_id).first.brand_name %></td>
        <td><%= event.notes %></td>
        <td class="btn-center"><%= link_to 'More Information', event, id:event.student_id, class: "btn btn-primary btn-small" %></td>
        <% end %>
      </tr>
    <% end %>
  <% end %>
  <% end %>
  </tbody>
</table>
<div class="pagination">
  <%= will_paginate @events, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
</div>

app/views/events/show.html.erb
<% content_for(:html_title) { "Event Information" } %>
<%= stylesheet_link_tag    'events', media: 'all' %>

<div class = 'container'>
<p>
  <strong>Time:</strong>
  <%= time_tag(@event.time, format: '%B %d, %Y %H:%M') %>
</p>

<% if @current_user.role == 'Nurse' %>
  <p>
    <strong>Student:</strong>
    <%= @event.student_id %> --
  <!--  <%#= User.where(role: "student", role_id: @event.student_id).first.first_name %> <%#= User.where(role: "student", role_id: @event.student_id).first.last_name %> ---->
    <%= link_to 'Student Information', User.where(role: "student", role_id: @event.student_id).first, class: "btn btn-primary btn-small" %>
  </p>
<% end %>
<p>
  <strong>Medication:</strong>
  <%= Medication.where(id: @event.med_id).first.brand_name %> --
  <%= link_to 'More Information', Medication.where(id: @event.med_id).first, class: "btn btn-primary btn-small" %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @event.amount %>
</p>

<p>
  <strong>Complete:</strong>
  <% if @event.complete %>
    Yes --
  <% else %>
    No --
  <% end %>
  <% if @current_user.role == 'Nurse' %>
    <% if @event.complete%>
      <%= link_to "Mark Incomplete", events_incomplete_path(:id => @event.id, :student_id => @event.student_id, :med_id => @event.med_id, :amount => @event.amount, :district_id => @event.district), class: "btn btn-primary btn-small" %>
    <% else %>
      <%= link_to "Mark Complete", events_complete_path(:id => @event.id, :student_id => @event.student_id, :med_id => @event.med_id, :amount => @event.amount, :district_id => @event.district), class: "btn btn-primary btn-small" %>
    <% end %>
  <% end %>
</p>

  <div class="field">
    <% if @current_user.role == 'Nurse' %>
      <%= form_for :notes, :url => events_change_notes_path do |f| %>
        <div class="field">
          <strong><%= f.label :notes, "Notes:" %></strong>
          <%= f.text_area :notes, value: @event.notes ,class: "form-control", :required => true, id:"notes" %>
          <%= f.hidden_field :id, value: @event.id %>
          <%= f.hidden_field :complete, value: @event.complete, class: "field" %>
        </div>
        <%= f.submit :Submit, class: "btn btn-primary", id:"submit" %>
        <%= link_to 'Back', events_path, {class: 'btn btn-secondary'} %>
      <% end %>
    <% else %>
      <b><%= label_tag 'Notes: '%></b>
      <p><%= @event.notes %></p>
    <% end %>

  </div>


<%#= link_to 'Edit', edit_event_path(@event) %>
</div>