config/routes.rb
Rails.application.routes.draw do
  resources :requests
  get 'users/register'

  get 'home/contact'

  get 'home/medications'

  get 'home/about'

  get 'home/index'

  post 'home/send_contact_message'

  post 'medications/set_page_count'

  post 'medications/search_meds'

  post 'inventories/set_page_count'

  post 'inventories/search_inv'

  post 'events/set_page_count'

  post 'events/search_events'

  get 'events/past_events'

  get 'events/parent_past_events'

  get 'events/student_past_events'

  get 'events/student_view'

  get 'events/parent_view'

  post 'events/set_past_page_count'

  post 'events/search_past_events'

  get 'events/complete'

  get 'events/incomplete'

  post 'events/change_notes'

  post 'users/register_district_admin'

  post 'users/update'

  get 'users/dashboard'

  get 'inventories/new'

  post 'inventories/new_item'

  post 'inventories/change_notes'

  post 'inventories/change_amount'

  post 'users/set_password'

  post 'users/create_and_email'

  get 'forms/new'

  post 'forms/new_form'

  post 'forms/search_forms'

  post 'forms/set_page_count'

  post 'forms/change_body'

  get 'forms/parent_view'

  get 'forms/parent_view'

  get 'forms/approve_form'

  post 'requests/create_request'

  post 'requests/approve'

  get 'nurses/associate_page', to: 'nurses#associate'
  post 'nurses/associate', to: 'nurses#associatestudentparent'

  get 'admins/associate_page', to: 'admins#associate'
  post 'admins/associate', to: 'admins#associatestudentparent'

  resources :password_sets
  resources :forms
  resources :events
  resources :inventories
  resources :medications, only: [:index, :show]
  resources :admins, only: [:index]
  resources :nurses, only: [:index]
  resources :students, only: [:index]
  resources :parents, only: [:index]
  resources :users

  root "home#index"

  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match "*path" => "home#index", via: [:get, :post]

end

app/controllers/nurses_controller.rb
class NursesController < ApplicationController
  before_action :is_nurse, only: [:index, :associate]
  after_action :clear_search


  # GET /nurses
  # GET /nurses.json
  def index
    if @current_user.nil? || @current_user.role != 'Nurse'
      flash[:error] = 'Please login as a Nurse.'
      redirect_to login_path
    else
      @nurse = @current_user
      @pending_requests = Array.new
      @pending_requests = Request.where(district_id: @nurse.district_id, nurse_approved: false)
    end
  end

  def clear_search
    session[:search_term] = nil
  end

  def associate
    district_id = User.where(role: "Nurse", id: @current_user.id)[0].district_id

    @parents = User.where(district_id: district_id, role: "Parent")
    @parents_info = []
    @parents.each do |x|
      @parents_info.push([x.first_name + " " + x.last_name, x.role_id])
    end
    @students_info = []
    @students = User.where(district_id: district_id, role: "Student")
    @students.each do |x|
      @students_info.push([x.first_name + " " + x.last_name, x.role_id])
    end
  end

  def associatestudentparent
    parent_info = params[:parent]
    parent_id = parent_info
    parent = Parent.find(parent_id)

    student_info = params[:student]
    student_id = student_info
    student = Student.find(student_id)

    if student.in?(parent.students)
      flash[:notice] = 'Student and Parent are already associated'
      redirect_to nurses_associate_page_path and return
    end
    parent.students << [student]
    flash[:notice] = 'Student and Parent successfully associated'

    redirect_to nurses_associate_page_path and return
  end

  private

  def is_nurse
    if @current_user.nil?
      # There is no logged in user
      flash[:warning] = "You must be logged in as a nurse to access this page."
      redirect_to home_index_path
    else
      # The user is logged in
      unless @current_user.role == 'Nurse'
        # The user is not a nurse
        flash[:warning] = "You must be a registered nurse to access this page."
        redirect_to home_index_path
      end
    end
  end
end

app/views/nurses/associate.html.erb
<div class="container rounded bg-white mt-5 mb-5">
  <div class="row">
    <div class="col-md-3 border-right">
    </div>
    <div class="col-md-5 border-right">
      <div class="p-3 py-5">
        <div class="d-flex justify-content-between align-items-center mb-3">
          <h3>Associate a Parent and Student</h3>
        </div>
        <%= form_for nurses_associate_page_path, url:nurses_associate_path do %>

          <div class="form-outline mb-4">
            <%= label_tag :parent, "Parent", class:"form-label" %>
            <%= select_tag :parent, options_for_select(@parents_info), class:"form-control" %>
          </div>
          <div class="form-outline mb-4">
            <%= label_tag :student, "Student", class:"form-label" %>
            <%= select_tag :student, options_for_select(@students_info), class:"form-control" %>
          </div>

          <div class="mt-5 text-center">
            <%=link_to "Cancel", nurses_path, class:"btn btn-danger profile-button"%>
            <%= submit_tag 'Submit', name: 'submit', class:"btn btn-primary profile-button"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/nurses/index.html.erb
<% content_for(:html_title) { "Nurse Dashboard" } %>
<%= stylesheet_link_tag    'nurses', media: 'all' %>

<main role="main">
  <div class="jumbotron">
    <div class="container mb">
      <h1 class="display-3 ">Welcome, <%= @current_user.first_name %></h1>
      <p>Click the button below to see upcoming events. You can also browse the dashboard for information on students, medications, past events, and more.</p>
      <%= link_to "Upcoming Events", events_path, class: "btn btn-primary btn-lg"%>
    </div>
  </div>

  <div class="container">
    <% unless @pending_requests.empty? %>
      <table class="table text-center mt-4">
        <tr class="table-warning">
          <td class="h5 w-70">You have medication requests awaiting your approval.</td>
          <td class="w-30"><%= link_to "View Requests for Approval", requests_path, class: "btn btn-warning profile-button", id: 'view-requests' %></td>
        </tr>
      </table>
    <% end %>
    <!-- Example row of columns -->
    <div class="album py-5">
      <div class="container homeContainer">
    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        <h2 class="top-content">View Past Events</h2>
        <%= link_to "Past Events", events_past_events_path, class: "btn btn-secondary"%>
        </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        <h2 class="top-content">View Parents and Students</h2>
        <%= link_to "People", users_path, class: "btn btn-secondary"%>
      </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        <h2 class="top-content">See Medication Information</h2>
        <%= link_to "All Medications", medications_path, class: "btn btn-secondary"%>
      </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        <h2 class="top-content">Create an Event</h2>
        <%= link_to "New Event", new_event_path, class: "btn btn-secondary"%>
      </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        <h2 class="top-content">Create a Form</h2>
        <%= link_to "New Form", forms_new_path, class: "btn btn-secondary"%>
      </div>
      </div>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
        <h2 class="top-content">View Forms</h2>
        <%= link_to "Forms", forms_path, class: "btn btn-secondary"%>
      </div>
      </div>
    </div>
        <div class="row justify-content-center">
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <h2 class="top-content">Associate Students with Parents</h2>
              <%= link_to "Association", nurses_associate_page_path, class: "btn btn-secondary"%>
            </div>
          </div>
          <div class="col-md-4">
            <div class="card mb-4 box-shadow">
              <h2 class="top-content">View Inventory</h2>
              <%= link_to "Inventory", inventories_path, class: "btn btn-secondary"%>
            </div>
          </div>
          <div class="col-md-4">
          </div>
        </div>
      </div>
    </div>
    <hr>

  </div> <!-- /container -->
</main>