config/routes.rb
Rails.application.routes.draw do
  resources :requests
  get 'users/register'

  get 'home/contact'

  get 'home/medications'

  get 'home/about'

  get 'home/index'

  post 'home/send_contact_message'

  post 'medications/set_page_count'

  post 'medications/search_meds'

  post 'inventories/set_page_count'

  post 'inventories/search_inv'

  post 'events/set_page_count'

  post 'events/search_events'

  get 'events/past_events'

  get 'events/parent_past_events'

  get 'events/student_past_events'

  get 'events/student_view'

  get 'events/parent_view'

  post 'events/set_past_page_count'

  post 'events/search_past_events'

  get 'events/complete'

  get 'events/incomplete'

  post 'events/change_notes'

  post 'users/register_district_admin'

  post 'users/update'

  get 'users/dashboard'

  get 'inventories/new'

  post 'inventories/new_item'

  post 'inventories/change_notes'

  post 'inventories/change_amount'

  post 'users/set_password'

  post 'users/create_and_email'

  get 'forms/new'

  post 'forms/new_form'

  post 'forms/search_forms'

  post 'forms/set_page_count'

  post 'forms/change_body'

  get 'forms/parent_view'

  get 'forms/parent_view'

  get 'forms/approve_form'

  post 'requests/create_request'

  post 'requests/approve'

  get 'nurses/associate_page', to: 'nurses#associate'
  post 'nurses/associate', to: 'nurses#associatestudentparent'

  get 'admins/associate_page', to: 'admins#associate'
  post 'admins/associate', to: 'admins#associatestudentparent'

  resources :password_sets
  resources :forms
  resources :events
  resources :inventories
  resources :medications, only: [:index, :show]
  resources :admins, only: [:index]
  resources :nurses, only: [:index]
  resources :students, only: [:index]
  resources :parents, only: [:index]
  resources :users

  root "home#index"

  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete
  match "*path" => "home#index", via: [:get, :post]

end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :set_form, only: [:show, :destroy]
  before_action :is_nurse, only: [:new, :new_form, :change_body, :index]
  after_action :clear_search, only: [:new, :new_form, :change_body]
  before_action :is_parent, only: [:parent_view]

  # GET /forms
  # GET /forms.json
  def index
    @pages = session[:page_count]
    @selection = session[:search_term]
    if @current_user.role == 'Nurse'
      if @pages.nil?
        if @selection.nil? or @selection.blank?
          @forms = Form.where(districtID: @current_user.district_id).page(params[:page]).per_page(50)
        else
          @forms = Form.where(districtID: @current_user.district_id).where('body LIKE ?', @selection).all.page(params[:page]).per_page(50)
        end
      else
        if @selection.nil? or @selection.blank?
          @forms = Form.where(districtID: @current_user.district_id).page(params[:page]).per_page(@pages)
        else
          @forms = Form.where(districtID: @current_user.district_id).where('body LIKE ?', @selection).all.page(params[:page]).per_page(@pages)
        end
      end
    elsif @current_user.role == 'Parent'
      @parent = Parent.find(@current_user.role_id)
      @forms = Array.new
      unless @parent.nil?
        @parent.students.each do |student|
          user = User.where(role_id: student.id, role: 'Student').first
          Form.where(studentID: user.id, parent_approved: false).each do |form|
            @pending_forms << form
          end
        end
      end
    end
  end

  # GET /forms/parent_view
  def parent_view
    @pages = session[:page_count]
    @selection = session[:search_term]
    @students = User.where(role: "Student", role_id: Parent.where(id: @current_user.role_id).first.student_ids).all
    unless @students.nil?
      @ids = @students.map{|s| s.id}
      if @pages.nil?
        if @selection.nil? or @selection.blank?
          @forms = Form.where(districtID: @current_user.district_id, studentID: @ids).page(params[:page]).per_page(50)
        else
          @forms = Form.where(districtID: @current_user.district_id, studentID: @ids).where('body LIKE ?', @selection).all.page(params[:page]).per_page(50)
        end
      else
        if @selection.nil? or @selection.blank?
          @forms = Form.where(districtID: @current_user.district_id, studentID: @ids).page(params[:page]).per_page(@pages)
        else
          @forms = Form.where(districtID: @current_user.district_id, studentID: @ids).where('body LIKE ?', @selection).all.page(params[:page]).per_page(@pages)
        end
      end
    else
      flash[:warning] = "You have no students. Please contact the district admin."
    end
    render 'forms/index'
  end


  #GET /forms/approve_form
  def approve_form
    @id = params[:id]
    @form = Form.where(id: @id).first
    if @form.nil?
      flash[:error] = "There was a problem approving this form. Please contact the district admin."
      redirect_to :back
    else
    Form.where(id: @id).first.update(parent_approved: true)
    flash[:notice] = "Form has been successfully approved"
    redirect_to forms_parent_view_path
    end
  end

  def set_page_count
    unless params[:page_count].nil?
      @pages = params[:page_count][:page_count]
      session[:page_count] = @pages.to_i
    end
    redirect_to forms_path
  end

  def search_forms
    unless params[:search_term].nil?
      @search = params[:search_term][:search_term]
      session[:search_term] = @search
    end
    redirect_to forms_path
  end

  def clear_search
    session[:search_term] = nil
  end


  # POST /form/change_body
  def change_body
    if params[:body].nil?
      flash[:error] = "There was a problem editing this form"
      redirect_to :back
    else
      @newBody = params[:body][:body]
      @id = params[:body][:id]
      @item = Form.where(id: @id).update_all(body: @newBody, parent_approved: false)
      flash[:notice] = "Form has been successfully updated. Guardian will have to approve again."
      redirect_to forms_path
    end
  end

  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
  end

  # POST /forms/new_form
  def new_form
    @form = params[:form]
    if @form.nil?
      flash[:error] = "There was a problem creating this form"
      redirect_to :back
    else
      @studentName = @form[:studentName]
      @body = @form[:body]
      if @studentName.blank?
        flash[:warning] = "You must select a student for this form"
        redirect_to :back and return
      end
      if @body.blank?
        flash[:warning] = "You cannot submit a blank form"
        redirect_to :back and return
      end
      @studentName = @studentName.split
      @fname = @studentName[0]
      @lname = @studentName[1]
      Form.create!(nurse_approved: true, body: @body, studentID: User.where(first_name: @fname, last_name: @lname).first.id, parent_approved: false, districtID: @current_user.district_id)
      flash[:notice] = "Form has been successfully created pending guardian approval"
      redirect_to nurses_path
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:nurse_approved, :parent_approved, :complete_boolean, :body)
    end

    def is_nurse
      if @current_user.nil?
        # There is no logged in user
        flash[:warning] = "You must be logged in as a nurse to access this page."
        redirect_to home_index_path
      else
        # The user is logged in
        unless @current_user.role == 'Nurse'
          # The user is not a nurse
          flash[:warning] = "You must be a registered nurse to access this page."
          redirect_to home_index_path
        end
      end
    end

  def is_parent
    if @current_user.nil?
      # There is no logged in user
      flash[:warning] = "You must be logged in as a parent to access this page."
      redirect_to home_index_path
    else
      # The user is logged in
      unless @current_user.role == "Parent"
        # The user is not a nurse
        flash[:warning] = "You must be a parent to access this page."
        redirect_to home_index_path
      end
    end
  end
end

app/views/forms/_form.html.erb
<%= form_for(@form) do |f| %>
  <% if @form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@form.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
      <% @form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nurse_approved %><br>
    <%= f.check_box :nurse_approved %>
  </div>
  <div class="field">
    <%= f.label :parent_approved %><br>
    <%= f.check_box :parent_approved %>
  </div>
  <div class="field">
    <%= f.label :complete_boolean %><br>
    <%= f.text_field :complete_boolean %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_field :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<% content_for(:html_title) { "Edit Form" } %>


<h1>Editing Form</h1>

<%= render 'form' %>

<%= link_to 'Show', @form %> |
<%= link_to 'Back', forms_path %>

app/views/forms/index.html.erb
<% content_for(:html_title) { "Forms" } %>
<%= stylesheet_link_tag    'events', media: 'all' %>
<script src="https://kit.fontawesome.com/9c8e310799.js" crossorigin="anonymous"></script>

<div class="container">
  <% if District.where(id: @current_user.district_id).first.nil? %>
    <h1>Forms</h1>
  <% else %>
    <h1>Forms for <%= District.where(id: @current_user.district_id).first.district_name %></h1>
  <% end %>
  <% if @current_user.role == 'Nurse' %>
    <div class="input-group">
      <%= form_for :search_term, url: forms_search_forms_path do |f|  %>
        <div class="input-group">
          <%= f.text_field :search_term, class: "form-control", :html => {:id => "form1", :name => "form1"}, id:"form1" %>
          <%= f.submit :Search, class: "btn btn-primary",  id: "submit"%>
        </div>
      <% end %>
    </div>
    <div class="d-flex flex-row align-items-center mt-2 justify-content-end">
      <div>
        <%= link_to 'Create a new Form', forms_new_path, class: "btn btn-primary btn-small" %>
      </div>
      <%= form_for :page_count, :url => forms_set_page_count_path do |f|  %>
        <div class="form-group"
        <%= f.label :page_count, "Results per page: " %>
        <%= f.select :page_count, options_for_select([10, 25, 35, 50, 75, 100, 250], @pages), {}, :onchange => 'this.form.submit()'%>
        </div>
      <% end %>
      </div>
  <% end %>
  <div class="mt-2">
    <table id="dtBasicExample" class="table table-striped table-bordered table-sm" cellspacing="0" width="100%">
      <thead>
      <tr>
        <th class="th-sm">Form ID
        </th>
        <th class="th-sm">Student Name
        </th>
        <th class="th-sm">Approved by Guardian
        </th>
        <th class="th-sm">Approved by Nurse
        </th>
        <th class="th-sm">Form Contents
        </th>
        <th class="th-sm">More Information
        </th>
      </tr>
      </thead>
      <tbody>
      <% @forms.each do |item| %>
        <% @student = User.where(id: item.studentID).first %>
        <tr>
          <td><%= item.id %></td>
          <% if @student.nil? %>
            <td>Test Form</td>
          <% else %>
            <td><%= @student.first_name + ' ' + @student.last_name %></td>
          <% end %>
          <td><% if item.parent_approved %>
              <span style="font-size: 25px; color: green;"><i class="fas fa-check-circle"></i></span>
            <% else %>
              <span style="font-size: 25px; color: red;"><i class="fas fa-times-circle"></i></span>
            <% end %></td>
          <td><% if item.nurse_approved %>
              <span style="font-size: 25px; color: green;"><i class="fas fa-check-circle"></i></span>
            <% else %>
              <span style="font-size: 25px; color: red;"><i class="fas fa-times-circle"></i></span>
            <% end %></td>
          <td><%= item.body %></td>
          <td class="btn-center"><%= link_to 'More Information', item, id:item.id, class: "btn btn-primary btn-small" %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="pagination">
    <%= will_paginate @inventory, renderer: WillPaginate::ActionView::BootstrapLinkRenderer%>
  </div>

app/views/forms/new.html.erb
<% content_for(:html_title) { "New Form" } %>
<%= stylesheet_link_tag    'contact', media: 'all' %>

<div class="container">
<!--Section heading-->
<h2 class="h1-responsive font-weight-bold text-center my-4">New Form</h2>
<!--Section description-->
<p class="text-center w-responsive mx-auto mb-5">Fill out the fields below to create a new form. All fields are required.</p>
<!--Grid column-->
<%= form_for :form, :url => forms_new_form_path do |f|  %>
  <div class="row">
    <div class="md-form mb-2">
      <% @students = User.where(role: "Student", district_id: @current_user.district_id).map{|s| s.first_name + " " + s.last_name } %>
      <%= f.label :studentName, "Name of Student for Form:" %><br>
      <%= f.select :studentName, @students, {}, class: "form-select", id: "studentName"%>
    </div>
  </div>
  <div class="row">
    <div class="md-form">
      <%= f.label :body, "Form Body:" %>
      <% @nurse = User.where(id: @current_user.id).first %>
      <% @name = @nurse.first_name + ' ' + @nurse.last_name %>
      <%= f.text_area :body, :html => {:id => "body", :name => "body"}, class: "form-control md-textarea", id:"body",
                      value: "The following form is to be approved by medical faculty and a student guardian in compliance with district and state policy. Please review all below information carefully and contact the district for any problems or to request changes.\n
                      Form created by: #{@name}\n
                      -----------------------------------------------\n\n\n
                      -----------------------------------------------\n
                      Please click below to approve this form." %>
    </div>
  </div>
  <div class="text-center text-md-left mt-2 mb-2">
    <%= f.submit :Submit, class: "btn btn-primary", id:"submit" %>
  </div>
<% end %>
</div>

app/views/forms/show.html.erb
<% content_for(:html_title) { "Form Information" } %>
<%= stylesheet_link_tag    'events', media: 'all' %>

<div class = 'container'>
  <p>
    <strong>Student: </strong>
    <% if @form.studentID.nil? %>
      This is a testing form with no assigned student
    <% else %>
      <% @student = User.where(id: @form.studentID).first%>
      <%= @student.first_name + " " + @student.last_name + " " + "(ID: " + @student.id.to_s + ")" %> --
      <%= link_to 'More Information', @student, class: "btn btn-primary btn-small" %>
    <% end %>
  </p>

  <p>
  <strong> Form approved by Guardian: </strong>
    <% if @form.parent_approved %>
      Yes
    <% else %>
      No
    <% end %>
  </p>

  <p>
    <strong> Form approved by Nurse: </strong>
    <% if @form.nurse_approved %>
      Yes
    <% else %>
      No
    <% end %>
  </p>

  <% if @current_user.role == "Nurse" %>
  <div class="field">
    <%= form_for :body, :url => forms_change_body_path do |f| %>
      <div class="field">
        <strong><%= f.label :body, "Form Body:" %></strong>
        <%= f.text_area :body, value: @form.body ,class: "form-control", id:"body", :required => true %>
        <%= f.hidden_field :id, value: @form.id %>
      </div>
      <%= f.submit :Submit, class: "btn btn-primary", id:"submit" %>

    <% end %>
    <% else %>
    <strong> Form Contents: </strong><br>
    <p><%= @form.body %></p><br>
    <% if @form.parent_approved %>
      <p>This form has already been approved</p>
      <% else %>
    <%= link_to 'Approve Form', forms_approve_form_path(:id => @form.id), class: "btn btn-primary btn-small" %>
    <% end %>
    <% end %>
  </div>

</div>